export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const LOG_OUT = 'LOG_OUT'
export const GET_QUESTIONS = 'GET_QUESTIONS'
export const REGISTER_VOTE = 'REGISTER_VOTE'
export const ADD_QUESTION = 'ADD_QUESTION'
export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'
